### PR TITLE
Submit av-core-0.6.1.js

### PR DESCRIPTION
**Pull request by habren**
This javascript is provided to support integration with Lean Cloud.

### CODE REVIEW

**Comment by Xuanwo** [comment]
Please remove the comment: https://github.com/staticfile/static/pull/320/files#diff-96925fde1542bf0dd66b9f2826b433c0R6

**Comment by habren** [comment]
@Xuanwo Comments are removed

**Comment by habren** [comment]
@Xuanwo Is there anything need to update? If not, please help to merge the commit. Thanks

**Comment by Xuanwo** [comment]
Sorry for delay.

**Comment by habren** [comment]
@Xuanwo  Thanks for your merge. But I can' find it on staticfile.org by searching 'av-core'

**Comment by Xuanwo** [comment]
server in qiniu will auto update in 3 am (utc +8) everyday, and maybe you
need to wait for sometime , sorry.

habren <notifications@github.com>于2016年3月15日 周二 14:43写道：

**Comment by habren** [comment]
@Xuanwo Got it. Thanks

**Comment by habren** [comment]
@Xuanwo After two days waiting, I still can not find it on staticfile.org by searching 'av-core'.

**Comment by Xuanwo** [comment]
Let me check with qiniu.

**Comment by habren** [comment]
@Xuanwo Any feedback? I still can't find it now

**Comment by Xuanwo** [comment]
@habren now you can use it in http://cdn.staticfile.org/av-core/0.6.1/av-core-mini.js or https://staticfile.qnssl.com/av-core/0.6.1/av-core-mini.js .

Sorry for the delay and we updated our update script, and now it looks OK.

**Comment by habren** [comment]
@Xuanwo Many thanks, I can access it with the links now. I'm wondering why I still can not search it on www.staticfile.org

**Comment by Xuanwo** [comment]
@habren There are still some wrong on our search model, you can search `av` to find `av-core` but `av-core` can't. I tried to do something for this.

**Pull request merged**
