### PR TITLE
add AdminLTE lib to staticfile.org

### PR DESCRIPTION
**Pull request by Kinghack**
Thanks.

### CODE REVIEW

**Comment by Xuanwo** [comment]
will be update at 3:00 am tomorrow.

**Comment by Kinghack** [comment]
Fantastic speed! Thanks.

**Comment by Kinghack** [comment]
have not deploy yet? Couldn't search the result.

**Comment by Xuanwo** [comment]
可能是延迟： http://cdn.staticfile.org/AdminLTE/2.3.0/Gruntfile.js
你可以根据如上目录结构直接调用~

搜索功能还有些问题，我们在想办法~

**Comment by Kinghack** [comment]
OK.

**Pull request merged**
